### PR TITLE
Make charge faster

### PR DESCRIPTION
**Pull request by aviraxp**
Haha guys, I am back!

I think the charge rate is too slow for me, so tweak it!

These commits are from my friend who tweaks it and the charge rate improves a lot!

### CODE REVIEW

**Comment by aviraxp** [comment]
Sorry for not merging them into one because I am not at computer.

**Comment by xdevs23** [comment]
Very nice, thank you!

**Comment by xdevs23** [comment]
Btw, no problem, the commits are squashed ;)

**Comment by regalstreak** [comment]
very good @aviraxp :+1:

**Pull request merged**
